<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="abc-PC" name="tests.RespondViaMailTest" tests="5" failures="1" timestamp="21 Nov 2017 11:25:42 GMT" time="127.625" errors="0">
  <testcase name="respondingViaMailNotLogin" time="31.431" classname="tests.RespondViaMailTest"/>
  <testcase name="verifyStatusLink" time="0.147" classname="tests.RespondViaMailTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
expected [true] but found [false], expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false], expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at steps.ActiveProjectsSteps.verifyingStatusLnkSteps(ActiveProjectsSteps.java:105)
	at tests.RespondViaMailTest.verifyStatusLink(RespondViaMailTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- verifyStatusLink -->
  <testcase name="sendQuery" time="45.392" classname="tests.RespondViaMailTest"/>
  <testcase name="verifyQueryLink" time="11.465" classname="tests.RespondViaMailTest"/>
  <testcase name="respondingViaMailWhileLogin" time="39.190" classname="tests.RespondViaMailTest"/>
</testsuite> <!-- tests.RespondViaMailTest -->
